### PR TITLE
increase the font size

### PR DESCRIPTION
**Pull request by Shibu-goswami**

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
@Shibu-goswami can you please justify this change?

**Comment by pedro-mendonca** [comment]
@Shibu-goswami feel free to open an issue and explain this change.
I'll close this for now.

**Comment by Shibu-goswami** [comment]
Hey just accept my PR please

**Comment by pedro-mendonca** [comment]
Hi, this doesn't make any sense.
Why should I increase the font size?

**Pull request closed without merging**
